In [1]:
!pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/nightly/cpu

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip


In [2]:
import torch
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

tensor([1.], device='mps:0')


In [3]:
from torch import nn

class MyLayer(nn.Module):
    
    def __init__(self):
        super(MyLayer, self).__init__()
        self.fc1 = nn.Linear(100, 2000)
        self.fc2 = nn.Linear(2000, 4000)
        self.fc3 = nn.Linear(4000, 1000)
        self.fc4 = nn.Linear(1000, 100)
        self.relu = nn.ReLU()
    
    def forward(self, x: torch.Tensor):   
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.relu(self.fc3(x))
        x = self.relu(self.fc4(x))
        return x
    
class MyModel(nn.Module):
    
    def __init__(self):
        super(MyModel, self).__init__()
        self.layer1 = MyLayer()
        self.layer2 = MyLayer()
        self.layer3 = MyLayer()
        self.layer4 = MyLayer()
        self.layer5 = MyLayer()
    
    def forward(self, x: torch.Tensor):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)
        x = self.layer5(x)
        return x

x = torch.randn(1000000, 100)


In [4]:
# time the cpu execution
import time
model = MyModel()
start = time.time()
model(x)
end = time.time()
print ("CPU time: ", end - start)

: 

: 

In [ ]:
# time the mps time
model = MyModel().to(mps_device)
x = x.to(mps_device)
start = time.time()
model(x)
print(x)
end = time.time()
print ("MPS time: ", end - start)

tensor([[-1.0190, -0.7741, -0.6327,  ..., -0.0260,  0.9239, -0.0504],
        [ 1.0060, -2.4891,  0.6296,  ..., -0.1953,  0.1445, -1.0096],
        [ 1.9329,  2.2892,  0.8806,  ...,  0.9866,  0.5983, -1.2860],
        ...,
        [ 0.3389, -1.5301, -1.2768,  ...,  0.4686,  1.4708, -0.6532],
        [-0.6551,  0.7626, -0.2547,  ..., -0.5057,  1.1011,  1.2686],
        [-2.0001, -1.0053, -0.7251,  ..., -0.0189,  0.2463,  0.0708]],
       device='mps:0')
MPS time:  0.3383669853210449


In [ ]:
# time the cpu execution
import time
x = x.to("cpu")
model = MyModel()
start = time.time()
model(x)
print(x)
end = time.time()
print ("CPU time: ", end - start)

tensor([[-1.0190, -0.7741, -0.6327,  ..., -0.0260,  0.9239, -0.0504],
        [ 1.0060, -2.4891,  0.6296,  ..., -0.1953,  0.1445, -1.0096],
        [ 1.9329,  2.2892,  0.8806,  ...,  0.9866,  0.5983, -1.2860],
        ...,
        [ 0.3389, -1.5301, -1.2768,  ...,  0.4686,  1.4708, -0.6532],
        [-0.6551,  0.7626, -0.2547,  ..., -0.5057,  1.1011,  1.2686],
        [-2.0001, -1.0053, -0.7251,  ..., -0.0189,  0.2463,  0.0708]])
CPU time:  1.1790399551391602


In [ ]:
# time the mps time
model = MyModel().to(mps_device)
x = x.to(mps_device)
start = time.time()
model(x)
print(x)
end = time.time()
print ("MPS time: ", end - start)

tensor([[-1.0190, -0.7741, -0.6327,  ..., -0.0260,  0.9239, -0.0504],
        [ 1.0060, -2.4891,  0.6296,  ..., -0.1953,  0.1445, -1.0096],
        [ 1.9329,  2.2892,  0.8806,  ...,  0.9866,  0.5983, -1.2860],
        ...,
        [ 0.3389, -1.5301, -1.2768,  ...,  0.4686,  1.4708, -0.6532],
        [-0.6551,  0.7626, -0.2547,  ..., -0.5057,  1.1011,  1.2686],
        [-2.0001, -1.0053, -0.7251,  ..., -0.0189,  0.2463,  0.0708]],
       device='mps:0')
MPS time:  0.31161069869995117
